# Generated by Django 5.0.1 on 2024-01-26 07:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="id_playground",
        ),
        migrations.AddField(
            model_name="playground",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="playground",
            name="height",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/playground_images/"
            ),
        ),
        migrations.AddField(
            model_name="playground",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="playground",
            name="reservation_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="updated_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="playground",
            name="width",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/user_images/"
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "admin_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("total_price", models.FloatField(default=0)),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "playground",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.playground",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.customuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playground",
            name="bookings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playground_bookings",
                to="booking.booking",
            ),
        ),
    ]
